// Cuate — brand tokens. Generated by design/brand/color.py. Do not hand-edit.
// The eight in-app themes still paint the interface; these paint the brand.
import SwiftUI

enum Brand {
    enum Ramp {
        static let ambar: [Int: Color] = [
            50: Color(hex: 0xFFF6EC), 100: Color(hex: 0xFFEAD3), 200: Color(hex: 0xFFD7A9), 300: Color(hex: 0xFFC37A), 400: Color(hex: 0xFFB24D), 500: Color(hex: 0xF9A211), 600: Color(hex: 0xD88B00), 700: Color(hex: 0xB07000), 800: Color(hex: 0x835200), 900: Color(hex: 0x553400), 950: Color(hex: 0x341E00)
        ]
        static let cielo: [Int: Color] = [
            50: Color(hex: 0xF2F6FA), 100: Color(hex: 0xE3EBF3), 200: Color(hex: 0xCAD7E5), 300: Color(hex: 0xACBFD2), 400: Color(hex: 0x839DB5), 500: Color(hex: 0x5C7A96), 600: Color(hex: 0x47647F), 700: Color(hex: 0x344E65), 800: Color(hex: 0x24384B), 900: Color(hex: 0x162431), 950: Color(hex: 0x0B151E)
        ]
        static let piedra: [Int: Color] = [
            50: Color(hex: 0xFCFAF7), 100: Color(hex: 0xF3EFEB), 200: Color(hex: 0xE1DDD8), 300: Color(hex: 0xCBC6C1), 400: Color(hex: 0xAFAAA5), 500: Color(hex: 0x908B86), 600: Color(hex: 0x726E69), 700: Color(hex: 0x544F4A), 800: Color(hex: 0x39342F), 900: Color(hex: 0x221D18), 950: Color(hex: 0x110C07)
        ]
        static let verde: [Int: Color] = [
            50: Color(hex: 0xEFF9F0), 100: Color(hex: 0xDCF0DE), 200: Color(hex: 0xBDE1C1), 300: Color(hex: 0x9ACDA0), 400: Color(hex: 0x73B37C), 500: Color(hex: 0x51995D), 600: Color(hex: 0x3A8248), 700: Color(hex: 0x286835), 800: Color(hex: 0x194D25), 900: Color(hex: 0x0E3316), 950: Color(hex: 0x061F0B)
        ]
        static let rojo: [Int: Color] = [
            50: Color(hex: 0xFFF2F1), 100: Color(hex: 0xFFE2DF), 200: Color(hex: 0xFFC6C0), 300: Color(hex: 0xFFA49B), 400: Color(hex: 0xF18178), 500: Color(hex: 0xDA6058), 600: Color(hex: 0xBE4842), 700: Color(hex: 0x9B332F), 800: Color(hex: 0x762220), 900: Color(hex: 0x501413), 950: Color(hex: 0x320A09)
        ]
    }

    struct Tokens {
        let bg: Color
        let surface: Color
        let surface_raised: Color
        let border: Color
        let border_interactive: Color
        let text: Color
        let text_secondary: Color
        let text_muted: Color
        let accent: Color
        let accent_hover: Color
        let accent_pressed: Color
        let accent_quiet: Color
        let accent_ink: Color
        let on_accent: Color
        let twin: Color
        let twin_quiet: Color
        let focus: Color
        let success: Color
        let danger: Color
    }

    static let dark = Tokens(
        bg: Color(hex: 0x08070C),
        surface: Color(hex: 0x110C07),
        surface_raised: Color(hex: 0x221D18),
        border: Color(hex: 0x39342F),
        border_interactive: Color(hex: 0x726E69),
        text: Color(hex: 0xFEFCF2),
        text_secondary: Color(hex: 0xCBC6C1),
        text_muted: Color(hex: 0x908B86),
        accent: Color(hex: 0xF9A211),
        accent_hover: Color(hex: 0xFFB24D),
        accent_pressed: Color(hex: 0xD88B00),
        accent_quiet: Color(hex: 0x341E00),
        accent_ink: Color(hex: 0xF9A211),
        on_accent: Color(hex: 0x08070C),
        twin: Color(hex: 0x839DB5),
        twin_quiet: Color(hex: 0x0B151E),
        focus: Color(hex: 0xFFB24D),
        success: Color(hex: 0x73B37C),
        danger: Color(hex: 0xF18178)
    )

    static let light = Tokens(
        bg: Color(hex: 0xFEFCF2),
        surface: Color(hex: 0xFCFAF7),
        surface_raised: Color(hex: 0xFFFFFF),
        border: Color(hex: 0xE1DDD8),
        border_interactive: Color(hex: 0x908B86),
        text: Color(hex: 0x110C07),
        text_secondary: Color(hex: 0x544F4A),
        text_muted: Color(hex: 0x726E69),
        accent: Color(hex: 0xF9A211),
        accent_hover: Color(hex: 0xFFB24D),
        accent_pressed: Color(hex: 0xD88B00),
        accent_quiet: Color(hex: 0xFFEAD3),
        accent_ink: Color(hex: 0x835200),
        on_accent: Color(hex: 0x110C07),
        twin: Color(hex: 0x344E65),
        twin_quiet: Color(hex: 0xE3EBF3),
        focus: Color(hex: 0xB07000),
        success: Color(hex: 0x286835),
        danger: Color(hex: 0x9B332F)
    )
}
